package com.depainspring.proj.service.util;

public interface MessageManagerConstants {

    String BUNDLE_NAME = "messages.properties";
    String SERVLET_EXCEPTION_ERROR_MESSAGE = "SERVLET_EXCEPTION_ERROR_MESSAGE";
    String IO_EXCEPTION_ERROR_MESSAGE = "IO_EXCEPTION_ERROR_MESSAGE";
    String LOGIN_SAVE_PROBLEM_MESSAGE = "LOGIN_SAVE_PROBLEM_MESSAGE";
    String LOGIN_PASSWORD_PROBLEM_MESSAGE = "LOGIN_PASSWORD_PROBLEM_MESSAGE";
    String DEPTITLE_SAVE_PROBLEM_MESSAGE = "DEPTITLE_SAVE_PROBLEM_MESSAGE";
    String EMPTY_FIELD_MESSAGE = "EMPTY_FIELD_MESSAGE";
    String INVALID_EMAIL_MESSAGE = "INVALID_EMAIL_MESSAGE";
    String FAILED_PASS_CONFIRMATION_MESSAGE = "FAILED_PASS_CONFIRMATION_MESSAGE";
    String INVALID_DATE_MESSAGE = "INVALID_DATE_MESSAGE";
    String NEW_EMPLOYEE_SAVE_SUCCESS_MESSAGE = "NEW_EMPLOYEE_SAVE_SUCCESS_MESSAGE";
    String EMPLOYEE_RECORD_UPDATE_SUCCESS_MESSAGE = "EMPLOYEE_RECORD_UPDATE_SUCCESS_MESSAGE";
    String NEW_DEP_SAVE_SUCCESS_MESSAGE = "NEW_DEP_SAVE_SUCCESS_MESSAGE";
    String DEP_RECORD_UPDATE_SUCCESS_MESSAGE = "DEP_RECORD_UPDATE_SUCCESS_MESSAGE";


}
